# Generated by Django 5.1.4 on 2025-01-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cedula', 'Cedula'), ('Cedula de extranjeria', 'Cedula de extranjeria')], max_length=25)),
                ('documento', models.CharField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_uso', models.CharField(choices=[('Departamental', 'Departamental'), ('Municipal', 'Municipal')], max_length=25)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cedula', 'Cedula'), ('Cedula de extranjeria', 'Cedula de extranjeria')], max_length=25)),
                ('documento', models.CharField(max_length=100, unique=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='core.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=100, unique=True)),
                ('numero_vehiculo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Activo', max_length=25)),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En curso', 'En curso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=25)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=25)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empleado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_venta', to='core.empleado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asiento')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='ViajePiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_piloto', models.CharField(choices=[('Principal', 'Principal'), ('Copiloto', 'Copiloto')], max_length=25)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viaje')),
            ],
        ),
    ]
