# Generated by Django 5.1.4 on 2025-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
