# Generated by Django 5.1.4 on 2025-01-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleado_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlantico', 'Atlantico'), ('Bogota', 'Bogota'), ('Bolivar', 'Bolivar'), ('Boyaca', 'Boyaca'), ('Caldas', 'Caldas'), ('Caqueta', 'Caqueta'), ('Casanara', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Choco', 'Choco'), ('Cordoba', 'Cordoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainia', 'Guainia'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Norte de Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindio', 'Quindio'), ('Risaralda', 'Risaralda'), ('San Andres y Providencia', 'San Andres y Providencia'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupes', 'Vaupes'), ('Vichada', 'Vichada')], max_length=100),
        ),
    ]
